### ISSUE TITLE
What is the meaning of CRAVAT

### ISSUE THREAD

**Issue by diekhans** [KarchinLab/open-cravat-readthedocs#4]
I can't find it in the documentation, so I am even more curious.  What does CRAVAT stand for.

Nice thing for the main page.

**Comment by RachelKarchin** [comment]
Originally was Cancer-Related Analysis of VAriants Toolkit
Since a few annotation modules now focus on diseases other than cancer, we changed it to
Custom-Ranked Analysis of VAriants Toolkit
We'll look into putting this on the main page!
