### ISSUE TITLE
oc run: error: argument -t: invalid choice: 'vcf'

### ISSUE THREAD

**Issue by gianfilippo** [KarchinLab/open-cravat-readthedocs#5]
Hi,

I am getting the error below because of using "vcf" as choice for the "-t" argument. 
oc run: error: argument -t: invalid choice: 'vcf' (choose from 'text', 'excel')

But on the web page (https://github.com/KarchinLab/open-cravat-readthedocs/blob/master/2.-Command-line-usage.rst) towards the end, the paragrapher "oc run | Run a job" suggests that the "vcf" is a proper choice.

Perhaps I am misunderstanding. Can you please clarify ?
Thanks

**Comment by kmoad** [comment]
It looks like the `vcfreporter` module wasn't part of the default installation. We'll add it to the next release.

For now, you can run `oc module install vcfreporter` to get it.

**Comment by gianfilippo** [comment]
Thanks!
